export const KEYS = {
  login: "login",
  getMe: "getMe",
  forgotPassword: "forgotPassword",
  register: "register",
  company: 'company',
  companyCategory: 'companyCategory',
  country: 'country',
  subscription: 'subscription',
  permits: 'permits',
  docTypes: 'docTypes',
  employee: 'employee',
  computerStatus: 'computerStatus',
  department: 'department',
  attandances: 'attandances',
  hikvision: 'hikvision',
  employeeType: 'employeeType',
  hikvisionLogs: 'hikvisionLogs',
  productivity: 'productivity',
  uploadEmployeeImg: 'uploadEmployeeImg',
}
