export const URLS = {
  login: '/api/auth/local',
  getMe: '/api/users/me',
  forgotPassword: '/api/auth/forgot-password',
  register: '/api/auth/local/register',
  company: '/api/companies',
  companyCategory: '/api/company-categories',
  country: '/api/countries',
  subscription: '/api/subscribe-types',
  permits: '/api/permits',
  docTypes: '/api/doc-types',
  employee: '/api/employees',
  computerStatus: '/api/computer-statuses',
  department: '/api/departments',
  attandances: '/api/attandances',
  hikvision: '/api/hikvisions',
  employeeType: '/api/employee-types',
  assignHikvision: '/api/hikvision/user/create',
  hikvisionLogs: '/api/hikvision/event/logs',
  productivity: '/api/productivity-categories',
}
